#!/bin/bash

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
  if [ -f "$PID_FILE" ]; then
    echo "$PROCESS_NAME is already started."
  else
    echo $$ > "$PID_FILE"
    echo "$PROCESS_NAME started"
    ./manage_my_process
  fi
}

stop_process() {
  if [ -f "$PID_FILE" ]; then
    kill "$(cat "$PID_FILE")"
    rm "$PID_FILE"
    echo "$PROCESS_NAME stopped"
  else
    echo "$PROCESS_NAME is not running."
  fi
}

restart_process() {
  stop_process
  start_process
  echo "$PROCESS_NAME restarted"
}

case $1 in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac

