#!/bin/bash

# Find the PID of the '4-to_infinity_and_beyond' process
PID=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$PID" ]; then
  # Send termination signal to the process
  kill "$PID"
fi

