#!/bin/bash

# Check if an IP address argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the command line argument
ip_address="$1"

# Perform the ping operation 5 times
ping -c 5 "$ip_address"
