#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and different messages for specific loop iterations

counter=1

while [ $counter -le 20 ]
do
  case $counter in
    4)
      echo "$counter"
      echo "bad luck from China"
      ;;
    9)
      echo "$counter"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$counter"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$counter"
      ;;
  esac

  counter=$((counter + 1))
done
